# Update amplify_outputs.json after successful deployment
# Run this script AFTER the Amplify build completes successfully

Write-Host "Checking for new amplify_outputs.json..." -ForegroundColor Cyan

# Check if the root amplify_outputs.json exists (generated by deployment)
if (Test-Path ".\amplify_outputs.json") {
    Write-Host "Found amplify_outputs.json in root directory" -ForegroundColor Green
    
    # Backup the old file
    if (Test-Path ".\client\src\amplify_outputs.json") {
        Copy-Item ".\client\src\amplify_outputs.json" ".\client\src\amplify_outputs.json.backup" -Force
        Write-Host "Backed up old file to client/src/amplify_outputs.json.backup" -ForegroundColor Yellow
    }
    
    # Copy new file to client/src
    Copy-Item ".\amplify_outputs.json" ".\client\src\amplify_outputs.json" -Force
    Write-Host "✅ Updated client/src/amplify_outputs.json" -ForegroundColor Green
    
    # Check if Milestone model is in the new file
    $content = Get-Content ".\client\src\amplify_outputs.json" -Raw
    if ($content -match "Milestone") {
        Write-Host "✅ Milestone model found in new amplify_outputs.json!" -ForegroundColor Green
        Write-Host "`nNext steps:" -ForegroundColor Cyan
        Write-Host "1. Restart your development server (npm start)" -ForegroundColor Yellow
        Write-Host "2. Try creating a milestone again" -ForegroundColor Yellow
    } else {
        Write-Host "⚠️  WARNING: Milestone model NOT found in amplify_outputs.json" -ForegroundColor Red
        Write-Host "The deployment may not have included the latest schema." -ForegroundColor Red
    }
} else {
    Write-Host "❌ amplify_outputs.json not found in root directory" -ForegroundColor Red
    Write-Host "`nThis means either:" -ForegroundColor Yellow
    Write-Host "1. The build hasn't completed yet - wait for it to finish" -ForegroundColor Yellow
    Write-Host "2. The build failed - check the Amplify Console" -ForegroundColor Yellow
    Write-Host "3. You need to download it manually from Amplify Console" -ForegroundColor Yellow
}
